In [ ]:
import pandas as pd
import mysql.connector
import matplotlib.pyplot as plt

conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='your_password',
    database='your_db'
)

df = pd.read_sql('SELECT * FROM employees', conn)

df.head()
df.info()
df.describe(include='all')

df.isnull().sum()
df.groupby('department')['salary'].mean().sort_values(ascending=False)
df.groupby('country')['salary'].mean()

df['department'].value_counts().plot(kind='bar', title='Employees per Department')
plt.show()
df['country'].value_counts().plot(kind='pie', autopct='%1.1f%%', title='Employees by Country')
plt.show()
df['salary'].plot(kind='hist', bins=20, title='Salary Distribution')
plt.show()

conn.close()