# Starter Jupyter Notebook for Teaching SQL

This notebook demonstrates how to:
1. Connect to a MySQL database
2. Load CSVs into MySQL tables
3. Run sample queries and display results with Pandas

---

In [ ]:
import pandas as pd
import mysql.connector
from sqlalchemy import create_engine

# Update connection details
USER = 'root'
PASSWORD = 'yourpassword'
HOST = 'localhost'
DB = 'teaching_db'

engine = create_engine(f'mysql+mysqlconnector://{USER}:{PASSWORD}@{HOST}/{DB}', echo=False)
conn = engine.connect()
print('Connected to MySQL database')

## Load CSV Data into MySQL (if not already loaded)
The schema must be created first (using `schema.sql`). Then load CSVs.

In [ ]:
import os

csv_dir = 'data'  # adjust path if needed

csv_files = {
    'customers': os.path.join(csv_dir, 'customers.csv'),
    'products': os.path.join(csv_dir, 'products.csv'),
    'sales': os.path.join(csv_dir, 'sales_100.csv')  # or sales_400.csv
}

for table, file in csv_files.items():
    df = pd.read_csv(file)
    df.to_sql(table, con=engine, if_exists='append', index=False)
    print(f'Loaded {len(df)} rows into {table}')

## Run Sample Queries

In [ ]:
# Example 1: list all customers
df = pd.read_sql("SELECT * FROM customers LIMIT 10;", conn)
df

In [ ]:
# Example 2: top 5 customers by total spending
query = """
SELECT c.name, SUM(s.price) AS total_spent
FROM sales s JOIN customers c ON s.customer_id=c.customer_id
GROUP BY c.name
ORDER BY total_spent DESC
LIMIT 5;
"""
df = pd.read_sql(query, conn)
df

In [ ]:
# Example 3: sales count per product category
query = """
SELECT p.category, COUNT(*) AS sales_cnt
FROM sales s JOIN products p ON s.product_id=p.product_id
GROUP BY p.category;
"""
df = pd.read_sql(query, conn)
df

---
You can now explore other queries from the `queries/instructor` or `queries/students` folders.